### server
GET http://localhost:5800


### unknown route
GET http://localhost:5800/unknown


### create a book
 POST http://localhost:5800/api/v1/example/books
 Content-Type: application/json

{
    "bookId": "44",
    "title": "Book Fourty four",
    "price": 12000
}


### get all books
GET http://localhost:5800/api/v1/example/books/

### get a book
GET http://localhost:5800/api/v1/example/books/44


### update a book
 PATCH http://localhost:5800/api/v1/example/books/44
 Content-Type: application/json

{
    "price": 1200
}


### delete a book
DELETE http://localhost:5800/api/v1/example/books/44