### server
GET http://localhost:5800


### unknown route
GET http://localhost:5800/unknown


### create new book
POST http://localhost:5800/api/books
Content-Type: application/json

{
    "bookId": 4,
    "title": "Book Four",
    "price": "1200"
}


### get all books
GET http://localhost:5800/api/books


### get a book
GET http://localhost:5800/api/books/2


### update a book
 PATCH http://localhost:5800/api/books/2
 Content-Type: application/json

{
    "price": 12000
}


### delete a book
DELETE http://localhost:5800/api/books/1